version: '3'
services:
  reverse-proxy:
    image: nginx:1.21.3
    container_name: reverse_proxy
    restart: on-failure
    volumes:
      - ./nginx/data:/usr/share/nginx/html:rw
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf/:rw
      - ./nginx/config/conf.d/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./nginx/logs:/var/log/nginx/:rw
      - ./nginx/ssl:/ssl/:rw
    ports:
      - "80:80"
      - "443:443"
    networks:
      project:
        ipv4_address: 172.23.40.4
networks:
  project:
    external:
      name: rvcomfort
